### ISSUE TITLE
Feature Request: Close on user click

### ISSUE THREAD

**Issue by jkardong** [ericjgagnon/wickedpicker#1]
### Description
The current procedure to use the WickedPicker is to instantiate the picker, selecting a time, and then clicking the X to close the picker window. When using the picker in a multi-step workflow, it becomes a hinder to the user to add a mouse click to close the picker. 

### Feature Request Description
After a user instantiates the picker and selects a time, a new function should close and record the time when the user clicks outside the picker window. 

### Current Behavior
1. User clicks inside a WickedPicker enabled text field
1. User selects a time
1. User clicks the X to close the picker window
1. Time is set in the text field

### New Behavior
1. User clicks inside a WickedPicker enabled text field
1. User selects a time
1. User clicks somewhere on website outside the picker (moves to next step in workflow)
1. Picker closes and time is set to text field.

**Comment by ericjgagnon** [comment]
I added this feature without removing the ability to also close the Wickedpicker by clicking the X.  Thanks for the feature request and interest in my project!
