### ISSUE TITLE
Ability to let user type time

### ISSUE THREAD

**Issue by berkandirim** [ericjgagnon/wickedpicker#11]
Is there a way to also let user type in the time either in the input or the popup box?

**Comment by berkandirim** [comment]
Ok, so I removed this on line 201 `$('.wickedpicker__controls__control--hours').focus(); `. Temp solution but it needs to be an option in the plugin.

**Comment by ericjgagnon** [comment]
Handling user input isn't something I want to add to the wickedpicker, but feel free to fork the project and add the feature.

**Comment by berkandirim** [comment]
I ended up using an input mask.
