### ISSUE TITLE
Can not clear date once picked

### ISSUE THREAD

**Issue by Gr84DarkMoon** [ericjgagnon/wickedpicker#13]
If someone where to click in a field with no data populated by accident, they are stuck with the time value.  perhaps a clear button, or the ability to type in the text box.

**Comment by Aendar** [comment]
Ideally I'd like to see the ability to click on the field without auto-populating the plugin's content. Then the field would only update when the user clicks to change the time. I'm looking into editing the source myself but a more universal option would be better I think.

**Comment by ericjgagnon** [comment]
Yeah, I can see how a  "fillTimeOnCreate" option would make sense.

**Comment by ericjgagnon** [comment]
I added a "clearable" option that wraps the input in div and adds a span containing an x that when clicked with clear the input field.
