### ISSUE TITLE
trigger on change event

### ISSUE THREAD

**Issue by pressmind** [ericjgagnon/wickedpicker#15]
hi eric,
perhaps you can add the change() event...

Line: 460 in wickedpicker.js

`        /*
         * Sets the give input's text to the current timepicker's time
         *
         * @param {object} The input element
         */
        setText: function (input) {
// old code
//$(input).val(this.formatTime(this.selectedHour, this.selectedMin, this.selectedMeridiem, this.selectedSec));

//  new code with change event
            $(input).val(this.formatTime(this.selectedHour, this.selectedMin, this.selectedMeridiem, this.selectedSec)).change();
        },`

merci! and great work!

**Comment by ericjgagnon** [comment]
Added!
