### ISSUE TITLE
Showing hours and minutes right-to-left

### ISSUE THREAD

**Issue by kamaladel** [ericjgagnon/wickedpicker#16]
Hello, 
I desgiend an interface which is mainly rtl, 
wickedpicker had been effected by that, showing hours on the right, and minutes on the left.

<img width="430" alt="screen shot 2016-06-09 at 17 06 43" src="https://cloud.githubusercontent.com/assets/18018410/15932505/ab9dd2d2-2e64-11e6-8f21-75addb31facf.png">

**Comment by ericjgagnon** [comment]
Honestly, I've never heard of a clock that is RTL.  I'm not certain that it even has a place in countries that read right to left.  If you need the functionality,  feel free to fork the project.
