### ISSUE TITLE
"now:" option is not always accurate 

### ISSUE THREAD

**Issue by fromoDev** [ericjgagnon/wickedpicker#25]
var options = {
        now: "12:35", //hh:mm 24 hour format only, defaults to current time

As stated in your comments the "now" time must be entered in 24 hour format. It all works well besides for when you enter  a time between 12:00 and 12:59 it gets treated as AM. Using 24 hour format it should be PM.

**Comment by ericjgagnon** [comment]
Yeah that is definitely a problem.  I'll pushing a fix now.  Thanks for pointing out the mistake.

**Comment by ericjgagnon** [comment]
Should be fixed in build 0.4.1

**Comment by fromoDev** [comment]
Thanx for the fix. I made the change. Works great now!
