### ISSUE TITLE
Feature Request: Add Seconds Selector

### ISSUE THREAD

**Issue by jkardong** [ericjgagnon/wickedpicker#3]
### Description
With the current WickedPicker, you can select HOUR and MINUTES. There has been a request made by my team to have the ability to select SECONDS as well. 

### Feature Request Description
Adding another section where the SECONDS can be added, from 01 to 59.

### Current Behavior
1. User clicks in WickedPicker enabled text field
1. User sets HOUR
1. User sets MINUTE
1. Time is set in the text field

### New Behavior
1. User clicks inside a WickedPicker enabled text field
1. User sets HOUR
1. User sets MINUTE
1. User set SECOND
1. Time is set in the text field

**Comment by ericjgagnon** [comment]
Added!
