### ISSUE TITLE
Popup Box Positions At Bottom Of Page

### ISSUE THREAD

**Issue by jkardong** [ericjgagnon/wickedpicker#5]
### Description
When opening the WickedPicker, the popup box opens at the bottom of the page, not below the text box it's attached to

### Expected Result
Opens directly to the side of text box

### Actual Result
Popup Box appears off page if page is long.

### Possible Cause
Could this be caused by competing CSS? If I want to adjust the position of the box, where should I do this?

**Comment by ericjgagnon** [comment]
I haven't used this on a really long page so I can't really visualize or experience what is happening with you project. I think it could be competing CSS, specifically I think you should take a look at this line https://github.com/ericjgagnon/wickedpicker/blob/master/src/wickedpicker.js#L107.  I'm setting the picker's position to be relative, its z-index to 1 greater than the input's, and then setting its top and left positions.

**Comment by Cha0s2nd** [comment]
On line https://github.com/ericjgagnon/wickedpicker/blob/master/src/wickedpicker.js#L111 the element.offsetHeight is undefined causing the top never to be set and for some reason element[0].offsetHeight works.

**Comment by jkardong** [comment]
Good catch. Added the element[0] and it started working on my project.

**Comment by ericjgagnon** [comment]
I cannot believe I make this mistake *face palm*
