### ISSUE TITLE
Manually setting the time on the picker

### ISSUE THREAD

**Issue by markandrewkato** [ericjgagnon/wickedpicker#67]
Hi,
I tried setting the time using $('.timepicker').val('10:00 AM'). This works but once I click the input field, the time changes. 
Is there a proper way to set the time on the picker?

Note: I've also tried adding spaces like so $('.timepicker').val('10 : 00 AM'), still changes when input field is clicked.

Thanks,
Mark

**Comment by jaimestuardo** [comment]
Please try my solution in https://github.com/ericjgagnon/wickedpicker/issues/74

**Comment by markandrewkato** [comment]
Hi @jaimestuardo!

I've already solved this problem. I did update the source code to add some features.

Thank you very much for your help. There might be some other people who can use your solution.

Have a great day ahead!
