### ISSUE TITLE
Time Changes to AM when WickedPicker is opened. 

### ISSUE THREAD

**Issue by jkardong** [ericjgagnon/wickedpicker#8]
### Description
When you click on a text field that is WickedPicker enabled, the time will change to AM no matter what time is set.

### Repro
1. In the WickedPicker index.html, change the init to the following
`$('.timepicker').wickedpicker({now: "14:25", twentyFour: false, title: 'My Timepicker', showSeconds: true});`
1. Open the index.html in a browser
1. Click on the text field
1. Note the time switches to AM

### Expected Result
Picker should not change the time

### Actual Result
If the time is PM, the picker will change it to AM

**Comment by ericjgagnon** [comment]
I see what you mean.  This will be resolved in the next commit.
