### ISSUE TITLE
Doesn't play well with Bootstrap tabs

### ISSUE THREAD

**Issue by jssuttles** [ericjgagnon/wickedpicker#9]
Hey, tried using this picker with bootstrap tabs. It caused the tabs to not function anymore.

**Comment by oshihirii** [comment]
I'm currently troubleshooting a bug where wickedpicker prevents on click events from occurring on nearby elements.  

I am wondering if wickedpicker is possibly being placed somehow *above* other div's, preventing the click event from registering?  

    <div class="wickedpicker" style="position: absolute; top: 274.8px; display: none; left: 729px;">

Unable to provide demonstration as it's a complex implementation.

**Comment by ericjgagnon** [comment]
I know this is a late response, but I have just recently tried it with Bootstrap v3.3.6 and I couldn't find any issues relating to tabs or click events on nearby elements.  If you can tell me which version of Bootstrap you are using, I can try it out.
